HOME_PAGE_URL = "https://stellarburgers.nomoreparties.site/"
FEED_PAGE_URL = "https://stellarburgers.nomoreparties.site/feed"
LOGIN_PAGE_URL = "https://stellarburgers.nomoreparties.site/login"
HISTORY_PAGE_URL = "https://stellarburgers.nomoreparties.site/account/order-history"
FORGOT_PASSWORD_URL = "https://stellarburgers.nomoreparties.site/forgot-password"
RESET_PASSWORD_URL = "https://stellarburgers.nomoreparties.site/reset-password"
